abbr -a cp 'cp -i'
abbr -a l 'ls -lah'
abbr -a mv 'mv -i'
abbr -a rm 'rm -i'
abbr -a tree 'tree -C'

abbr -a ga    'git add'
abbr -a gaa   'git add --all'
abbr -a gb    'git branch'
abbr -a gcb   'git checkout -b'
abbr -a gco   'git checkout'
abbr -a gcm   'git commit -m'
abbr -a gcv   'git commit -v'
abbr -a gd    'git diff'
abbr -a gds   'git diff --staged'
abbr -a glog  'git log --oneline --decorate -20'
abbr -a gloga 'git log --oneline --decorate --all -20'
abbr -a hb    'hub browse'
